version: "3.6"

services:
  openldap:
    image: vladchernikov/openldap
    volumes:
      - /var/lib/openldap
      - ./init:/docker-entrypoint-init
      - ./slapd.ldif:/etc/openldap/slapd.ldif
    environment:
      - FORCE_SLAPADD_CN_CONFIG_LDIF_FILE_PATH=/etc/openldap/slapd.ldif

  phpldapadmin:
    image: vladchernikov/phpldapadmin
    volumes:
      - ./config.php:/etc/phpldapadmin/config.php
    links:
      - openldap
    ports:
      - 80:80
